#!/bin/sh
#export PICO_SDK_PATH=~/pico-sdk
cmake -B build
cd build
make -j
cd ..
openocd -f interface/cmsis-dap.cfg -f target/rp2040.cfg -c "adapter speed 5000" -c "program build/mimik.elf verify reset exit"